set(MAILCORE2_CORE_HEADERS
	core/MCCore.h
	core/abstract/MCAbstract.h
	core/abstract/MCAbstractMessage.h
	core/abstract/MCAbstractMessagePart.h
	core/abstract/MCAbstractMultipart.h
	core/abstract/MCAbstractPart.h
	core/abstract/MCAddress.h
	core/abstract/MCMessageConstants.h
	core/abstract/MCMessageHeader.h
	core/basetypes/MCArray.h
	core/basetypes/MCAssert.h
	core/basetypes/MCAutoreleasePool.h
	core/basetypes/MCBaseTypes.h
	core/basetypes/MCBasicLock.h
	core/basetypes/MCConnectionLogger.h
	core/basetypes/MCData.h
	core/basetypes/MCDataDecoderUtils.h
	core/basetypes/MCDataStreamDecoder.h
	core/basetypes/MCDefines.h
	core/basetypes/MCHash.h
	core/basetypes/MCHashMap.h
	core/basetypes/MCHTMLCleaner.h
	core/basetypes/MCICUTypes.h
	core/basetypes/MCIndexSet.h
	core/basetypes/MCIterator.h
	core/basetypes/MCJSON.h
	core/basetypes/MCLibetpan.h
	core/basetypes/MCLibetpanTypes.h
	core/basetypes/MCLog.h
	core/basetypes/MCMD5.h
	core/basetypes/MCNull.h
	core/basetypes/MCObject.h
	core/basetypes/MCOperation.h
	core/basetypes/MCOperationCallback.h
	core/basetypes/MCOperationQueue.h
	core/basetypes/MCOperationQueueCallback.h
	core/basetypes/MCRange.h
	core/basetypes/MCSet.h
	core/basetypes/MCString.h
	core/basetypes/MCUtils.h
	core/basetypes/MCValue.h
	core/imap/MCIMAP.h
	core/imap/MCIMAPFolder.h
	core/imap/MCIMAPFolderStatus.h
	core/imap/MCIMAPIdentity.h
	core/imap/MCIMAPMessage.h
	core/imap/MCIMAPMessagePart.h
	core/imap/MCIMAPMultipart.h
	core/imap/MCIMAPNamespace.h
	core/imap/MCIMAPNamespaceItem.h
	core/imap/MCIMAPPart.h
	core/imap/MCIMAPProgressCallback.h
	core/imap/MCIMAPSearchExpression.h
	core/imap/MCIMAPSession.h
	core/imap/MCIMAPSyncResult.h
	core/nntp/MCNNTP.h
	core/nntp/MCNNTPGroupInfo.h
	core/nntp/MCNNTPProgressCallback.h
	core/nntp/MCNNTPSession.h
	core/pop/MCPOP.h
	core/pop/MCPOPMessageInfo.h
	core/pop/MCPOPProgressCallback.h
	core/pop/MCPOPSession.h
	core/provider/MCAccountValidator.h
	core/provider/MCMailProvider.h
	core/provider/MCMailProvidersManager.h
	core/provider/MCNetService.h
	core/provider/MCProvider.h
	core/renderer/MCAddressDisplay.h
	core/renderer/MCDateFormatter.h
	core/renderer/MCHTMLBodyRendererTemplateCallback.h
	core/renderer/MCHTMLRenderer.h
	core/renderer/MCHTMLRendererCallback.h
	core/renderer/MCRenderer.h
	core/rfc822/MCAttachment.h
	core/rfc822/MCMessageBuilder.h
	core/rfc822/MCMessageParser.h
	core/rfc822/MCMessagePart.h
	core/rfc822/MCMultipart.h
	core/rfc822/MCRFC822.h
	core/smtp/MCSMTP.h
	core/smtp/MCSMTPProgressCallback.h
	core/smtp/MCSMTPSession.h
)

set(MAILCORE2_ASYNC_HEADERS
	async/MCAsync.h
	async/imap/MCAsyncIMAP.h
	async/imap/MCIMAPAppendMessageOperation.h
	async/imap/MCIMAPAsyncConnection.h
	async/imap/MCIMAPAsyncSession.h
	async/imap/MCIMAPCapabilityOperation.h
	async/imap/MCIMAPCheckAccountOperation.h
	async/imap/MCIMAPCopyMessagesOperation.h
	async/imap/MCIMAPCustomCommandOperation.h
	async/imap/MCIMAPFetchContentOperation.h
	async/imap/MCIMAPFetchContentToFileOperation.h
	async/imap/MCIMAPFetchFoldersOperation.h
	async/imap/MCIMAPFetchMessagesOperation.h
	async/imap/MCIMAPFetchNamespaceOperation.h
	async/imap/MCIMAPFetchParsedContentOperation.h
	async/imap/MCIMAPFolderInfo.h
	async/imap/MCIMAPFolderInfoOperation.h
	async/imap/MCIMAPFolderStatusOperation.h
	async/imap/MCIMAPIdentityOperation.h
	async/imap/MCIMAPIdleOperation.h
	async/imap/MCIMAPMessageRenderingOperation.h
	async/imap/MCIMAPMoveMessagesOperation.h
	async/imap/MCIMAPOperation.h
	async/imap/MCIMAPOperationCallback.h
	async/imap/MCIMAPQuotaOperation.h
	async/imap/MCIMAPSearchOperation.h
	async/nntp/MCAsyncNNTP.h
	async/nntp/MCNNTPAsyncSession.h
	async/nntp/MCNNTPFetchAllArticlesOperation.h
	async/nntp/MCNNTPFetchArticleOperation.h
	async/nntp/MCNNTPFetchHeaderOperation.h
	async/nntp/MCNNTPFetchOverviewOperation.h
	async/nntp/MCNNTPFetchServerTimeOperation.h
	async/nntp/MCNNTPListNewsgroupsOperation.h
	async/nntp/MCNNTPOperation.h
	async/nntp/MCNNTPOperationCallback.h
	async/nntp/MCNNTPPostOperation.h
	async/pop/MCAsyncPOP.h
	async/pop/MCPOPAsyncSession.h
	async/pop/MCPOPFetchHeaderOperation.h
	async/pop/MCPOPFetchMessageOperation.h
	async/pop/MCPOPFetchMessagesOperation.h
	async/pop/MCPOPOperation.h
	async/pop/MCPOPOperationCallback.h
	async/smtp/MCAsyncSMTP.h
	async/smtp/MCSMTPAsyncSession.h
	async/smtp/MCSMTPOperation.h
	async/smtp/MCSMTPOperationCallback.h
)

if(NOT WIN32)
	set(MAILCORE2_OBJC_HEADERS
		objc/MCObjC.h
		objc/abstract/MCOAbstract.h
		objc/abstract/MCOAbstractMessage.h
		objc/abstract/MCOAbstractMessagePart.h
		objc/abstract/MCOAbstractMultipart.h
		objc/abstract/MCOAbstractPart.h
		objc/abstract/MCOAddress.h
		objc/abstract/MCOConstants.h
		objc/abstract/MCOHTMLRendererDelegate.h
		objc/abstract/MCOHTMLRendererIMAPDelegate.h
		objc/abstract/MCOMessageHeader.h
		objc/imap/MCOIMAP.h
		objc/imap/MCOIMAPAppendMessageOperation.h
		objc/imap/MCOIMAPBaseOperation.h
		objc/imap/MCOIMAPCapabilityOperation.h
		objc/imap/MCOIMAPCopyMessagesOperation.h
		objc/imap/MCOIMAPCustomCommandOperation.h
		objc/imap/MCOIMAPFetchContentOperation.h
		objc/imap/MCOIMAPFetchContentToFileOperation.h
		objc/imap/MCOIMAPFetchFoldersOperation.h
		objc/imap/MCOIMAPFetchMessagesOperation.h
		objc/imap/MCOIMAPFetchNamespaceOperation.h
		objc/imap/MCOIMAPFetchParsedContentOperation.h
		objc/imap/MCOIMAPFolder.h
		objc/imap/MCOIMAPFolderInfo.h
		objc/imap/MCOIMAPFolderInfoOperation.h
		objc/imap/MCOIMAPFolderStatus.h
		objc/imap/MCOIMAPFolderStatusOperation.h
		objc/imap/MCOIMAPIdentity.h
		objc/imap/MCOIMAPIdentityOperation.h
		objc/imap/MCOIMAPIdleOperation.h
		objc/imap/MCOIMAPMessage.h
		objc/imap/MCOIMAPMessagePart.h
		objc/imap/MCOIMAPMessageRenderingOperation.h
		objc/imap/MCOIMAPMoveMessagesOperation.h
		objc/imap/MCOIMAPMultipart.h
		objc/imap/MCOIMAPNamespace.h
		objc/imap/MCOIMAPNamespaceItem.h
		objc/imap/MCOIMAPOperation.h
		objc/imap/MCOIMAPPart.h
		objc/imap/MCOIMAPQuotaOperation.h
		objc/imap/MCOIMAPSearchExpression.h
		objc/imap/MCOIMAPSearchOperation.h
		objc/imap/MCOIMAPSession.h
		objc/nntp/MCONNTP.h
		objc/nntp/MCONNTPFetchAllArticlesOperation.h
		objc/nntp/MCONNTPFetchArticleOperation.h
		objc/nntp/MCONNTPFetchHeaderOperation.h
		objc/nntp/MCONNTPFetchOverviewOperation.h
		objc/nntp/MCONNTPFetchServerTimeOperation.h
		objc/nntp/MCONNTPGroupInfo.h
		objc/nntp/MCONNTPListNewsgroupsOperation.h
		objc/nntp/MCONNTPOperation.h
		objc/nntp/MCONNTPPostOperation.h
		objc/nntp/MCONNTPSession.h
		objc/pop/MCOPOP.h
		objc/pop/MCOPOPFetchHeaderOperation.h
		objc/pop/MCOPOPFetchMessageOperation.h
		objc/pop/MCOPOPFetchMessagesOperation.h
		objc/pop/MCOPOPMessageInfo.h
		objc/pop/MCOPOPOperation.h
		objc/pop/MCOPOPSession.h
		objc/provider/MCOAccountValidator.h
		objc/provider/MCOMailProvider.h
		objc/provider/MCOMailProvidersManager.h
		objc/provider/MCONetService.h
		objc/provider/MCOProvider.h
		objc/rfc822/MCOAttachment.h
		objc/rfc822/MCOMessageBuilder.h
		objc/rfc822/MCOMessageParser.h
		objc/rfc822/MCOMessagePart.h
		objc/rfc822/MCOMultipart.h
		objc/rfc822/MCORFC822.h
		objc/smtp/MCOSMTP.h
		objc/smtp/MCOSMTPOperation.h
		objc/smtp/MCOSMTPSendOperation.h
		objc/smtp/MCOSMTPSession.h
		objc/utils/MCOIndexSet.h
		objc/utils/MCOObjectWrapper.h
		objc/utils/MCOOperation.h
		objc/utils/MCORange.h
		objc/utils/MCOUtils.h
		objc/utils/NSArray+MCO.h
		objc/utils/NSData+MCO.h
		objc/utils/NSDictionary+MCO.h
		objc/utils/NSError+MCO.h
		objc/utils/NSIndexSet+MCO.h
		objc/utils/NSObject+MCO.h
		objc/utils/NSString+MCO.h
		objc/utils/NSValue+MCO.h
	)
endif()

set(public_headers
	MailCore.h
	${MAILCORE2_CORE_HEADERS}
	${MAILCORE2_ASYNC_HEADERS}
	${MAILCORE2_OBJC_HEADERS}
)
