name: Pull Request Check

on: pull_request

defaults:
  run:
    shell: zsh -l {0} # Use zsh iwth login as default shell

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  Android:
    name: "mailcore2 - Android"
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
    - name: Install NDK
      run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;26.2.11394342"
    - name: Install Swift 6.0.3 toolchain
      run: curl -L -O https://download.swift.org/swift-6.0.3-release/xcode/swift-6.0.3-RELEASE/swift-6.0.3-RELEASE-osx.pkg && sudo installer -pkg swift-6.0.3-RELEASE-osx.pkg -target /
    - name: Install Swift Android Toolchain
      run: wget https://github.com/readdle/swift-android-toolchain/releases/latest/download/swift-android.zip; unzip swift-android.zip;
    - name: Install Android Emulator
      run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-29;google_apis;x86_64"
    - name: Run connected android tests
      run: export ANDROID_NDK_ROOT_26C=$ANDROID_HOME/ndk/26.2.11394342;
        export SWIFT_ANDROID_HOME_6_0_3=$(pwd)/swift-android;
        ./build-scripts/test-android.sh
    - name: Publish Report
      uses: mikepenz/action-junit-report@v3
      if: failure()
      with:
        report_paths: .build/reports/junit.xml
        check_name: mailcore2 - Android - Report
        detailed_summary: true
        include_passed: true

  Darwin:
    name: "mailcore2 - ${{ matrix.os }}"
    runs-on: macos-latest
    timeout-minutes: 60

    strategy:
      matrix:
        os: [macOS, iOS]
        include:
          - os: macOS
            os_lowercased: macos
          - os: iOS
            os_lowercased: ios

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run tests
      run: ./build-scripts/test-${{ matrix.os_lowercased }}.sh
    - name: Publish Report
      uses: mikepenz/action-junit-report@v3
      if: failure()
      with:
        report_paths: .build/reports/junit.xml
        check_name: mailcore2 - ${{ matrix.os }} - Report
        detailed_summary: true
        include_passed: true
